flowercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('flowers/', views.flower_index, name='flower-index'),
    path('flowers/<int:flower_id>/', views.flower_detail, name='flower-detail'),
    path('flowers/create/', views.FlowerCreate.as_view(), name='flower-create'),
    path('flowers/<int:pk>/update/', views.FlowerUpdate.as_view(), name='flower-update'),
    path('flowers/<int:pk>/delete/', views.FlowerDelete.as_view(), name='flower-delete'),
    path(
        'flowers/<int:flower_id>/add-watering/', 
        views.add_watering, 
        name='add-watering'
    ),
    path('pots/create/', views.PotCreate.as_view(), name='pot-create'),
    path('pots/<int:pk>/', views.PotDetail.as_view(), name='pot-detail'),
    path('pots/', views.PotList.as_view(), name='pot-index'),
    path('pots/<int:pk>/update/', views.PotUpdate.as_view(), name='pot-update'),
    path('pots/<int:pk>/delete/', views.PotDelete.as_view(), name='pot-delete'),
    path('flowers/<int:flower_id>/associate-pot/<int:pot_id>/', views.associate_pot, name='associate-pot'),
    path('flowers/<int:flower_id>/remove-pot/<int:pot_id>/', views.remove_pot, name='remove-pot'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

TIMES = (
    ('M', 'Morning'),
    ('N', 'Noon'),
    ('E', 'Evening')
)

# Create your models here.
class Pot(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pot-detail', kwargs={'pk': self.id})
    


class Flower(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)

    pots = models.ManyToManyField(Pot)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("flower-detail", kwargs={"flower_id": self.id})
    



class Watering(models.Model):
    date = models.DateField('Watering date')
    time = models.CharField(
        max_length=1,
        choices=TIMES,
        default=TIMES[0][0]
    )
    
    flower = models.ForeignKey(Flower, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_time_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date'] 

main_app/forms.py
from django import forms
from .models import Watering

class WateringForm(forms.ModelForm):
    class Meta:
        model = Watering
        fields = ['date', 'time']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
# main_app/views.py

from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Flower, Pot
from .forms import WateringForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



def about(request):
    return render(request, 'about.html')


class Home(LoginView):
    template_name = 'home.html'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('flower-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )


@login_required
def flower_index(request):
    flowers = Flower.objects.filter(user=request.user)
    return render(request, 'flowers/index.html', {'flowers': flowers})

@login_required
def flower_detail(request, flower_id):
    flower = Flower.objects.get(id=flower_id)
    pots_flower_doesnt_have = Flower.objects.exclude(id__in = flower.pots.all().values_list('id'))
    watering_form = WateringForm()

    return render(request, 'flowers/detail.html', {
        'flower': flower,
        'watering_form': watering_form,
        'pots': pots_flower_doesnt_have
    })


class FlowerCreate(LoginRequiredMixin, CreateView):
    model = Flower
    fields = ['name', 'color']

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  
        # Let the CreateView do its job as usual
        return super().form_valid(form)


class FlowerUpdate(LoginRequiredMixin, UpdateView):
    model = Flower
    fields = ['color']


class FlowerDelete(LoginRequiredMixin, DeleteView):
    model = Flower
    success_url = '/flowers/'

@login_required
def add_watering(request, flower_id):
    # create a ModelForm instance using the data in request.POST
    form = WateringForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the flower_id assigned
        new_watering = form.save(commit=False)
        new_watering.flower_id = flower_id
        new_watering.save()
    return redirect('flower-detail', flower_id=flower_id)


class PotCreate(LoginRequiredMixin, CreateView):
    model = Pot
    fields = '__all__'


class PotList(LoginRequiredMixin, ListView):
    model = Pot


class PotDetail(LoginRequiredMixin, DetailView):
    model = Pot


class PotUpdate(LoginRequiredMixin, UpdateView):
    model = Pot
    fields = ['name', 'color']


class PotDelete(LoginRequiredMixin, DeleteView):
    model = Pot
    success_url = '/pots/'


@login_required
def associate_pot(request, flower_id, pot_id):
    Flower.objects.get(id=flower_id).pots.add(pot_id)
    return redirect('flower-detail', flower_id=flower_id)

@login_required
def remove_pot(request, flower_id, pot_id):
    Flower.objects.get(id=flower_id).pots.remove(pot_id)
    return redirect('flower-detail', flower_id=flower_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Flower Collector</h1>
<hr />
<p class="page-content">A collection of flowers!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Flower Collector</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/rose.svg' %}"
    />

    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img
            src="{% static 'images/lily.svg' %}"
            alt="The Flower Collector
          Logo"
            style="width: 80px; height: auto"
          />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'flower-index' %}">All Flowers</a></li>
          <li><a href="{% url 'pot-index' %}">All Pots</a></li>
          <li><a href="{% url 'flower-create' %}">Add a Flower</a></li>
          <li><a href="{% url 'pot-create' %}">Add a Pot</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
            {% else %}
          </li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/flowers/detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/flowers/flower-detail.css' %}" />
{% endblock %} {% block content %}
<section class="flower-container">
  <div class="flower-img">
    <img
      src="{% static 'images/bouquet.svg' %}"
      alt="A bouquet"
      style="width: 100px; height: auto"
    />
  </div>
  <div class="flower-details">
    <h1>{{ flower.name }}</h1>
    {% if flower %}
    <h2>A {{ flower.color }} {{ flower.name }}.</h2>
    {% else %}
    <h2>No flower here.</h2>
    {% endif %}
  </div>
  <div class="flower-actions">
    <a href="{% url 'flower-update' flower.id %}" class="btn warn">Edit</a>
    <a href="{% url 'flower-delete' flower.id %}" class="btn danger">Delete</a>
  </div>
</section>
<div class="watering-container">
  <h3>Water the Flower</h3>
  <form
    action="{% url 'add-watering' flower.id %}"
    method="post"
    class="subsection-content"
    autocomplete="off"
  >
    {% csrf_token %} {{ watering_form.as_p }}
    <button type="submit" class="btn submit">Water</button>
  </form>

  <div class="watering-container">
    <section class="waterings">
      <div class="subsection-title">
        <h2>Past Watering</h2>
        <img src="{% static 'images/bouquet.svg' %}" alt="A bouquet" />
        <img
          src="{% static 'images/watering.svg' %}"
          alt="A green watering can"
        />
      </div>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          {% for watering in flower.watering_set.all %}
          <tr>
            <td>{{watering.date}}</td>
            <td>{{watering.get_time_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </div>

  <section class="pots">
    <div class="subsection-title">
      <h2>Pots</h2>
      <img src="{% static 'images/pot.svg' %}" alt="A flower pot" />
    </div>

    <h3>{{ flower.name }}'s Pot</h3>
    <div class="subsection-content">
      {% if flower.pots %} {% for pot in flower.pots.all %}
      <div class="pot-container">
        <div
          class="color-block"
          style="background-color: {{ pot.color }}"
        ></div>
        <a href="{% url 'pot-detail' pot.id %}">
          <p>A {{ pot.color }} {{ pot.name }}</p>
        </a>
        <form action="{% url 'remove-pot' flower.id pot.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Remove Pot</button>
        </form>
      </div>
      {% endfor %} {% else %}
      <p class="no-pots">{{flower.name}} isn't in a pot!</p>
      {% endif %}
    </div>

    <h3>Available Pots</h3>
    <div class="subsection-content">
      {% if pots.count %} {% for pot in pots.all %}
      <div class="pot-container">
        <div
          class="color-block"
          style="background-color: {{ pot.color }}"
        ></div>
        <a href="{% url 'pot-detail' pot.id %}">
          <p>A {{ pot.color }} {{ pot.name }}</p>
        </a>
        <form action="{% url 'associate-pot' flower.id pot.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn submit">Put in Pot</button>
        </form>
      </div>
      {% endfor %} {% else %}
      <p class="all-pots">{{floower.name}} already has a pot!</p>
      {% endif %}
    </div>
  </section>
</div>

{% endblock %}

main_app/templates/flowers/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/flowers/flower-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Flower List</h1>
  <img src="{% static 'images/lily.svg' %}" alt="A lily flower" />
  <img src="{% static 'images/rose.svg' %}" alt="A red rose" />
  <img src="{% static 'images/poppy.svg' %}" alt="A red poppy" />
  <img src="{% static 'images/orchid.svg' %}" alt="A purple orchid" />
</section>

<section class="card-container">
  {% for flower in flowers %}
  <div class="card">
    <a href="{% url 'flower-detail' flower.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            src="{% static 'images/bouquet.svg' %}"
            alt="A bouquet"
            style="width: 100px; height: auto"
          />
        </div>
        <h2 class="card-title">{{ flower.name }}</h2>
        {% if flower %}
        <p>A {{ flower.color }} {{ flower.name }}.</p>
        {% else %}
        <p>No flowers here.</p>
        {% endif %}
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img
      src="{% static 'images/bouquet.svg' %}"
      alt="A bouquet of flowers"
      style="width: 300px; height: auto"
    />
  </div>
  <img
    src="{% static 'images/text.svg' %}"
    alt="Text reads: The Flower Collector"
  />
</section>

{% endblock %}

main_app/templates/main_app/flower_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header">
  <h1>Delete Flower?</h1>
  <img src="{% static 'images/bouquet.svg' %}" alt="A bouquet" />
</div>

<h2>Are you sure you want to delete {{ flower.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'flower-detail' flower.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/flower_form.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}

<div class="page-header">
  <!-- Check if a flower object exists to determine if we're editing -->
  {% if flower %}
  <h1>Edit {{ flower.name }}</h1>
  {% else %}
  <h1>Add a Flower</h1>
  {% endif %}
  <img src="{% static 'images/poppy.svg' %}" alt="A red poppy" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/pot_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header">
  <h1>Delete Pot?</h1>
  <img src="{% static 'images/pot.svg' %}" alt="A flower pot" />
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'pot-detail' pot.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/pot_detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pots/pot-detail.css' %}" />
{% endblock %} {% block content %}

<div class="card" style="border-color: {{ pot.color }}">
  <div class="card-bg" style="background-color: {{ pot.color }}"></div>
  <div class="card-content">
    <h2>{{ pot.name }}</h2>
    <p>A {{ pot.color }} pot.</p>
  </div>
</div>
<a href="{% url 'pot-update' pot.id %}" class="btn warn">Edit</a>
<a href="{% url 'pot-delete' pot.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/pot_form.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}
<div class="page-header">
  {% if object %}
  <h1>Edit {{object.name}}</h1>
  {% else %}
  <h1>Add a Pot</h1>
  {% endif %}
  <img src="{% static 'images/pot.svg' %}" alt="A flower pot" />
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/pot_list.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pots/pot-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>All Pots</h1>
  <img src="{% static 'images/pot.svg' %}" alt="A flower pot" />
</section>

<section class="card-container">
  {% for pot in pot_list %}
  <div class="card" style="border-color: {{ pot.color }}">
    <div class="card-bg" style="background-color: {{ pot.color }}"></div>
    <a href="{% url 'pot-detail' pot.id %}">
      <div class="card-content">
        <h2>{{ pot.name }}</h2>
        <p>A {{ pot.color }} {{ pot.name }} pot.</p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/bouquet.svg' %}" alt="A bouquet" />
</div>
{% if error_message %}
<p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}